# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Documents and Settings\Pocisk\.qgis\python\plugins\FocalStats\ui_focalstats.ui'
#
# Created: Tue Dec 27 15:19:16 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_FocalStats(object):
    def setupUi(self, FocalStats):
        FocalStats.setObjectName(_fromUtf8("FocalStats"))
        FocalStats.resize(448, 233)
        self.gridLayout_2 = QtGui.QGridLayout(FocalStats)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(FocalStats)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.cbLayers = QtGui.QComboBox(FocalStats)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbLayers.sizePolicy().hasHeightForWidth())
        self.cbLayers.setSizePolicy(sizePolicy)
        self.cbLayers.setEditable(True)
        self.cbLayers.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.cbLayers.setObjectName(_fromUtf8("cbLayers"))
        self.gridLayout_2.addWidget(self.cbLayers, 0, 1, 1, 2)
        self.groupBox = QtGui.QGroupBox(FocalStats)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.cbX = QtGui.QComboBox(self.groupBox)
        self.cbX.setObjectName(_fromUtf8("cbX"))
        self.cbX.addItem(_fromUtf8(""))
        self.cbX.addItem(_fromUtf8(""))
        self.cbX.addItem(_fromUtf8(""))
        self.cbX.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbX, 0, 2, 1, 1)
        self.cbY = QtGui.QComboBox(self.groupBox)
        self.cbY.setEnabled(False)
        self.cbY.setObjectName(_fromUtf8("cbY"))
        self.cbY.addItem(_fromUtf8(""))
        self.cbY.addItem(_fromUtf8(""))
        self.cbY.addItem(_fromUtf8(""))
        self.cbY.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbY, 0, 4, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.cbMethod = QtGui.QComboBox(self.groupBox)
        self.cbMethod.setObjectName(_fromUtf8("cbMethod"))
        self.cbMethod.addItem(_fromUtf8(""))
        self.cbMethod.addItem(_fromUtf8(""))
        self.cbMethod.addItem(_fromUtf8(""))
        self.cbMethod.addItem(_fromUtf8(""))
        self.cbMethod.addItem(_fromUtf8(""))
        self.cbMethod.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbMethod, 1, 1, 1, 2)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 3, 1, 1)
        self.sbIter = QtGui.QSpinBox(self.groupBox)
        self.sbIter.setEnabled(False)
        self.sbIter.setMinimum(1)
        self.sbIter.setObjectName(_fromUtf8("sbIter"))
        self.gridLayout.addWidget(self.sbIter, 1, 4, 1, 1)
        self.useY = QtGui.QCheckBox(self.groupBox)
        self.useY.setObjectName(_fromUtf8("useY"))
        self.gridLayout.addWidget(self.useY, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 4)
        self.cbAddResult = QtGui.QCheckBox(FocalStats)
        self.cbAddResult.setChecked(True)
        self.cbAddResult.setObjectName(_fromUtf8("cbAddResult"))
        self.gridLayout_2.addWidget(self.cbAddResult, 2, 0, 1, 4)
        self.label_2 = QtGui.QLabel(FocalStats)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.cbType = QtGui.QComboBox(FocalStats)
        self.cbType.setEnabled(False)
        self.cbType.setObjectName(_fromUtf8("cbType"))
        self.cbType.addItem(_fromUtf8(""))
        self.cbType.addItem(_fromUtf8(""))
        self.cbType.addItem(_fromUtf8(""))
        self.cbType.addItem(_fromUtf8(""))
        self.cbType.addItem(_fromUtf8(""))
        self.cbType.addItem(_fromUtf8(""))
        self.cbType.addItem(_fromUtf8(""))
        self.cbType.addItem(_fromUtf8(""))
        self.cbType.addItem(_fromUtf8(""))
        self.cbType.addItem(_fromUtf8(""))
        self.cbType.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cbType, 3, 3, 1, 1)
        self.eOutput = QtGui.QLineEdit(FocalStats)
        self.eOutput.setObjectName(_fromUtf8("eOutput"))
        self.gridLayout_2.addWidget(self.eOutput, 4, 0, 1, 3)
        self.bBrowse = QtGui.QPushButton(FocalStats)
        self.bBrowse.setObjectName(_fromUtf8("bBrowse"))
        self.gridLayout_2.addWidget(self.bBrowse, 4, 3, 1, 1)
        self.bCancel = QtGui.QPushButton(FocalStats)
        self.bCancel.setObjectName(_fromUtf8("bCancel"))
        self.gridLayout_2.addWidget(self.bCancel, 5, 3, 1, 1)
        self.bOK = QtGui.QPushButton(FocalStats)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bOK.sizePolicy().hasHeightForWidth())
        self.bOK.setSizePolicy(sizePolicy)
        self.bOK.setObjectName(_fromUtf8("bOK"))
        self.gridLayout_2.addWidget(self.bOK, 5, 2, 1, 1)
        self.bOpenRaster = QtGui.QPushButton(FocalStats)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bOpenRaster.sizePolicy().hasHeightForWidth())
        self.bOpenRaster.setSizePolicy(sizePolicy)
        self.bOpenRaster.setObjectName(_fromUtf8("bOpenRaster"))
        self.gridLayout_2.addWidget(self.bOpenRaster, 0, 3, 1, 1)
        self.cbDataType = QtGui.QCheckBox(FocalStats)
        self.cbDataType.setObjectName(_fromUtf8("cbDataType"))
        self.gridLayout_2.addWidget(self.cbDataType, 3, 2, 1, 1)
        self.lInfo = QtGui.QLabel(FocalStats)
        self.lInfo.setObjectName(_fromUtf8("lInfo"))
        self.gridLayout_2.addWidget(self.lInfo, 5, 0, 1, 2)

        self.retranslateUi(FocalStats)
        self.cbType.setCurrentIndex(5)
        QtCore.QObject.connect(self.useY, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cbY.setEnabled)
        QtCore.QObject.connect(self.bCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), FocalStats.close)
        QtCore.QObject.connect(self.cbDataType, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cbType.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(FocalStats)

    def retranslateUi(self, FocalStats):
        FocalStats.setWindowTitle(QtGui.QApplication.translate("FocalStats", "Focal Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("FocalStats", "Input raster:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("FocalStats", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FocalStats", "Neighborhood size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("FocalStats", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbX.setItemText(0, QtGui.QApplication.translate("FocalStats", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.cbX.setItemText(1, QtGui.QApplication.translate("FocalStats", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.cbX.setItemText(2, QtGui.QApplication.translate("FocalStats", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.cbX.setItemText(3, QtGui.QApplication.translate("FocalStats", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.cbY.setItemText(0, QtGui.QApplication.translate("FocalStats", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.cbY.setItemText(1, QtGui.QApplication.translate("FocalStats", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.cbY.setItemText(2, QtGui.QApplication.translate("FocalStats", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.cbY.setItemText(3, QtGui.QApplication.translate("FocalStats", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("FocalStats", "Operation:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbMethod.setItemText(0, QtGui.QApplication.translate("FocalStats", "Sum", None, QtGui.QApplication.UnicodeUTF8))
        self.cbMethod.setItemText(1, QtGui.QApplication.translate("FocalStats", "Average", None, QtGui.QApplication.UnicodeUTF8))
        self.cbMethod.setItemText(2, QtGui.QApplication.translate("FocalStats", "Median", None, QtGui.QApplication.UnicodeUTF8))
        self.cbMethod.setItemText(3, QtGui.QApplication.translate("FocalStats", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.cbMethod.setItemText(4, QtGui.QApplication.translate("FocalStats", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.cbMethod.setItemText(5, QtGui.QApplication.translate("FocalStats", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("FocalStats", "Iterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.useY.setText(QtGui.QApplication.translate("FocalStats", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAddResult.setText(QtGui.QApplication.translate("FocalStats", "Add result to map canvas", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("FocalStats", "Output raster:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbType.setItemText(0, QtGui.QApplication.translate("FocalStats", "Byte", None, QtGui.QApplication.UnicodeUTF8))
        self.cbType.setItemText(1, QtGui.QApplication.translate("FocalStats", "UInt16", None, QtGui.QApplication.UnicodeUTF8))
        self.cbType.setItemText(2, QtGui.QApplication.translate("FocalStats", "Int16", None, QtGui.QApplication.UnicodeUTF8))
        self.cbType.setItemText(3, QtGui.QApplication.translate("FocalStats", "UInt32", None, QtGui.QApplication.UnicodeUTF8))
        self.cbType.setItemText(4, QtGui.QApplication.translate("FocalStats", "Int32", None, QtGui.QApplication.UnicodeUTF8))
        self.cbType.setItemText(5, QtGui.QApplication.translate("FocalStats", "Float32", None, QtGui.QApplication.UnicodeUTF8))
        self.cbType.setItemText(6, QtGui.QApplication.translate("FocalStats", "Float64", None, QtGui.QApplication.UnicodeUTF8))
        self.cbType.setItemText(7, QtGui.QApplication.translate("FocalStats", "CInt16", None, QtGui.QApplication.UnicodeUTF8))
        self.cbType.setItemText(8, QtGui.QApplication.translate("FocalStats", "CInt32", None, QtGui.QApplication.UnicodeUTF8))
        self.cbType.setItemText(9, QtGui.QApplication.translate("FocalStats", "CFloat32", None, QtGui.QApplication.UnicodeUTF8))
        self.cbType.setItemText(10, QtGui.QApplication.translate("FocalStats", "CFloat64", None, QtGui.QApplication.UnicodeUTF8))
        self.bBrowse.setText(QtGui.QApplication.translate("FocalStats", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.bCancel.setText(QtGui.QApplication.translate("FocalStats", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.bOK.setText(QtGui.QApplication.translate("FocalStats", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.bOpenRaster.setText(QtGui.QApplication.translate("FocalStats", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.cbDataType.setText(QtGui.QApplication.translate("FocalStats", "Datat type", None, QtGui.QApplication.UnicodeUTF8))
        self.lInfo.setText(QtGui.QApplication.translate("FocalStats", "Status", None, QtGui.QApplication.UnicodeUTF8))

